name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./pulse_sound --file ./pulse_sound/Dockerfile --tag my-image-name:$(date +%s) && docker build ./mongodb --file ./mongodb/Dockerfile --tag my-image-name:$(date +%s)
 
